# Generated by Django 3.2.4 on 2022-05-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('secret', '*')], default='男', max_length=10, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('l_score', models.BigIntegerField(default=0, verbose_name='积分')),
                ('l_score_time', models.DateTimeField(auto_now=True, verbose_name='最新更新时间')),
                ('introduce', models.TextField(default='这个人太懒了，什么都没有留下', verbose_name='个人简介')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
